#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

echo -e "${GREEN}Running lint-staged...${NO_COLOR}"

if npx lint-staged; then
  echo -e "\n${GREEN}✔ Lint checks passed, commit created${NO_COLOR}"
  exit 0
else
  echo -e "\n${RED}✖ Lint checks failed, commit wasn't created${NO_COLOR}"
  exit 1
fi
