#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'

echo -e "${GREEN}Running ESLint...${NO_COLOR}"

if npm run lint-staged; then
  echo -e "${GREEN}ESLint passed${NO_COLOR}"
  exit 0
else
  echo -e "${RED}ESLint error${NO_COLOR}"
  exit 1
fi
